package com.example.recorderchunks.Audio_Models;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

public class ModelMetadata {
    public static JSONArray getModelMetadata() throws JSONException {
        String metadataJson = "["
                + "  {"
                + "    \"model_name\": \"vosk-model-small-en-us-0.15\","
                + "    \"size\": \"40M\","
                + "    \"language\": \"English\","
                + "    \"download_link\": \"https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip\""
                + "  },"
                + "  {"
                + "    \"model_name\": \"vosk-model-small-en-in-0.4\","
                + "    \"size\": \"36M\","
                + "    \"language\": \"Indian English\","
                + "    \"download_link\": \"https://alphacephei.com/vosk/models/vosk-model-small-en-in-0.4.zip\""
                + "  },"
                + "  {"
                + "    \"model_name\": \"vosk-model-small-cn-0.22\","
                + "    \"size\": \"42M\","
                + "    \"language\": \"Chinese\","
                + "    \"download_link\": \"https://alphacephei.com/vosk/models/vosk-model-small-cn-0.22.zip\""
                + "  },"
                + "  {"
                + "    \"model_name\": \"vosk-model-small-fr-0.22\","
                + "    \"size\": \"41M\","
                + "    \"language\": \"French\","
                + "    \"download_link\": \"https://alphacephei.com/vosk/models/vosk-model-small-fr-0.22.zip\""
                + "  },"
                + "  {"
                + "    \"model_name\": \"vosk-model-small-de-0.15\","
                + "    \"size\": \"45M\","
                + "    \"language\": \"German\","
                + "    \"download_link\": \"https://alphacephei.com/vosk/models/vosk-model-small-de-0.15.zip\""
                + "  },"
                + "  {"
                + "    \"model_name\": \"vosk-model-small-es-0.42\","
                + "    \"size\": \"39M\","
                + "    \"language\": \"Spanish\","
                + "    \"download_link\": \"https://alphacephei.com/vosk/models/vosk-model-small-es-0.42.zip\""
                + "  },"
                + "  {"
                + "    \"model_name\": \"vosk-model-small-it-0.22\","
                + "    \"size\": \"48M\","
                + "    \"language\": \"Italian\","
                + "    \"download_link\": \"https://alphacephei.com/vosk/models/vosk-model-small-it-0.22.zip\""
                + "  },"
                + "  {"
                + "    \"model_name\": \"vosk-model-small-nl-0.22\","
                + "    \"size\": \"39M\","
                + "    \"language\": \"Dutch\","
                + "    \"download_link\": \"https://alphacephei.com/vosk/models/vosk-model-small-nl-0.22.zip\""
                + "  },"
                + "  {"
                + "    \"model_name\": \"vosk-model-small-ar-tn-0.1-linto\","
                + "    \"size\": \"158M\","
                + "    \"language\": \"Arabic (Tunisian)\","
                + "    \"download_link\": \"https://alphacephei.com/vosk/models/vosk-model-small-ar-tn-0.1-linto.zip\""
                + "  },"
                + "  {"
                + "    \"model_name\": \"vosk-model-small-fa-0.42\","
                + "    \"size\": \"53M\","
                + "    \"language\": \"Farsi (Persian)\","
                + "    \"download_link\": \"https://alphacephei.com/vosk/models/vosk-model-small-fa-0.42.zip\""
                + "  },"
                + "  {"
                + "    \"model_name\": \"vosk-model-small-ja-0.22\","
                + "    \"size\": \"48M\","
                + "    \"language\": \"Japanese\","
                + "    \"download_link\": \"https://alphacephei.com/vosk/models/vosk-model-small-ja-0.22.zip\""
                + "  },"
                + "  {"
                + "    \"model_name\": \"vosk-model-small-hi-0.22\","
                + "    \"size\": \"42M\","
                + "    \"language\": \"Hindi\","
                + "    \"download_link\": \"https://alphacephei.com/vosk/models/vosk-model-small-hi-0.22.zip\""
                + "  },"
                + "  {"
                + "    \"model_name\": \"vosk-model-small-ko-0.22\","
                + "    \"size\": \"82M\","
                + "    \"language\": \"Korean\","
                + "    \"download_link\": \"https://alphacephei.com/vosk/models/vosk-model-small-ko-0.22.zip\""
                + "  },"
                + "  {"
                + "    \"model_name\": \"vosk-model-small-pl-0.22\","
                + "    \"size\": \"50M\","
                + "    \"language\": \"Polish\","
                + "    \"download_link\": \"https://alphacephei.com/vosk/models/vosk-model-small-pl-0.22.zip\""
                + "  },"
                + "  {"
                + "    \"model_name\": \"vosk-model-small-uz-0.22\","
                + "    \"size\": \"49M\","
                + "    \"language\": \"Uzbek\","
                + "    \"download_link\": \"https://alphacephei.com/vosk/models/vosk-model-small-uz-0.22.zip\""
                + "  }"
                + "]";
        return new JSONArray(metadataJson);
    }
}